version: '3'

services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

  # swapper_be:
  #   image: swapper_be
  #   restart: always
  #   env_file:
  #     - .env.prod
  #   depends_on:
  #     - postgres
  #     - redis
  #   build:
  #     context: .
  #     target: dependencies
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - ./:/home/node/app

  # swapper_fe:
  #   image: swapper_fe
  #   build: .
  #   depends_on:
  #     - swapper_be
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - API_URL=http://localhost:3333

volumes:
  database-data: # named volumes can be managed easier using docker-compose
  redis-data:
