version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 2345:5432

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  database-data: # named volumes can be managed easier using docker-compose
